- platform: time_date
  name: Uhrzeit
  display_options:
    - 'time'
- platform: rest
  name: 'Temperatur Schlafzimmer'
  resource: 'http://localhost:8080/api/v1/temperatures/bedroom'
  unit_of_measurement: "°C"
